env:
    MANIFEST: repo init -u https://github.com/yaap/manifest.git -b thirteen
    DEVICE: rosemary 
    OEM: xiaomi
    DT_LINK: https://github.com/Nukxx/android_device_xiaomi_rosemary.git
    DT_PATH: device/$OEM/$DEVICE
    SE_VT_LINK: https://github.com/Nukxx/device_mediatek_sepolicy_vndr.git
    SE_VT_PATH: device/mediatek/sepolicy_vndr 
    VT_LINK: https://github.com/Nukxx/proprietary_vendor_xiaomi_rosemary.git
    VT_PATH: vendor/$OEM/$DEVICE
    KT_LINK: https://github.com/Nukxx/android_kernel_xiaomi_mt6785.git
    PLATFORM: mt6785
    KT_PATH: kernel/$OEM/$PLATFORM
    CLANG_LINK: https://gitlab.com/tejassinggh/clang-r450784d.git
    CLANG_PATH: prebuilts/clang/host/linux-x86/clang-r450784d
    V_MTK_OS_LINK: https://github.com/Nukxx/vendor_mediatek-opensource.git
    V_MTK_OS_PATH: vendor/mediatek/opensource
    V_MTK_INTERF_LINK: https://github.com/Nukxx/vendor_mediatek_interfaces.git
    V_MTK_INTERF_PATH: vendor/mediatek/interfaces
    MTK_COM_LINK: https://github.com/Nukxx/device_mediatek_common.git
    MTK_COM_PATH: device/mediatek/common
    HW_MTK_LINK: https://github.com/Nukxx/android_hardware_mediatek.git
    HW_MTK_PATH: hardware/mediatek
    HW_XIMI_LINK: https://github.com/Nukxx/android_hardware_xiaomi.git
    HW_XIMI_PATH: hardware/xiaomi
    EXTRA_CMD: export SKIP_ABI_CHECKS=true
    LUNCH_COMBO: aosp_${DEVICE}-userdebug
    OUTPUT: aosp*.zip

task:
  name: "Setting Up, Syncing and Building ..."
  timeout_in: 240m
  container:
      image: apon77/aosp:latest
      cpu: 8
      memory: 32G


  Storage-Checker_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - mkdir -p ~/work
      - cd ~/work
      - mkdir p-404 && cd p-404
      - repo init -u https://github.com/P-404/android_manifest -b tokui
      - echo "ROM repo initialization successful"
      - repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
      - echo "ROM repo sync successful"
      - git clone $DT_LINK $DT_PATH
      - echo "git clone DT successful"
      - git clone $VT_LINK $VT_PATH
      - echo "git clone VT successful"
      - git clone $KT_LINK $KT_PATH
      - echo "git clone KT successful"
      - git clone $SE_VT_LINK $SE_VT_PATH 
      - echo "git clone SE_VT successful"
      - rm -r prebuilts/clang/host/linux-x86/clang-r450784d
      - echo "clang removed successfully"
      - git clone $CLANG_LINK $CLANG_PATH
      - echo "git clone CLANG successful"
      - git clone $V_MTK_OS_LINK $V_MTK_OS_PATH
      - echo "git clone V_MTK_OS successful"
      - git clone $V_MTK_INTERF_LINK $V_MTK_INTERF_PATH
      - echo "git clone V_MTK_INTERFACE successful"
      - git clone $MTK_COM_LINK $MTK_COM_PATH
      - echo "git clone MTK_COM successful"
      - git clone $HW_MTK_LINK $HW_MTK_PATH
      - echo "git clone HW_MTK successful"
      - git clone $HW_XIMI_LINK $HW_XIMI_PATH
      - echo "git clone HW_XIMI successful"
      - echo "==========================="
      - echo "Syncing Complete!"
      - echo "============================"

  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - cd ~/work
      - $EXTRA_CMD
      - export USE_CCACHE=1
      - export CCACHE_EXEC=/usr/bin/ccache
      - ccache -M 50G
      - source build/envsetup.sh
      - lunch p404_$devicecodename-userdebug
      - make bacon
     

Upload_script:
      - echo "============================"
      - echo "Uploading the Build..."
      - echo "============================"
      - cd ~/work
      - cd out/target/product/"$DEVICE"
      - ls -lh
      - pwd
      - chmod 777 * 
      - curl --upload-file $(echo $OUTPUT) https://transfer.sh | tee link.txt && echo " "
      - echo " "
      - echo "============================"
      - echo "Build Uploaded!"
      - echo "Please see the link Below-  "
      - echo "----------------------------"
      - cat link.txt && echo " "
      - echo "==========================" 
